### ISSUE TITLE
error: pathspec 'dotbot' did not match any file(s) known to git

### ISSUE THREAD

**Issue by felipecassiors** [anishathalye/dotfiles_template#15]
Hi, 

I just wanted to get started so I generated a repository from this template. Then:

```bash
git clone https://github.com/felipecassiors/dotfiles "$HOME/.dotfiles"
./dotfiles/install
```

And after running the install, this is the output:

```log
error: pathspec 'dotbot' did not match any file(s) known to git
```

I suspect this issue is due to how the GitHub Template works, because if you look at [my dotfiles repository generated by this](https://github.com/felipecassiors/dotfiles), there is no `dotbot` folder.

Am I the only one?

**Comment by felipecassiors** [comment]
To solve it, I can manually add the submodule, following these steps:

https://github.com/anishathalye/dotbot#integrate-with-existing-dotfiles

But I suppose the goal of this template repository is to not have to do that, right?

**Comment by anishathalye** [comment]
Yes, it seems that GitHub templates do not work with subodules. I've undone the change made in response to #13 -- this repository is no longer a template. Updated README in adc0f6865692764c45286dcf4f6d859faa03e938.

Thakn you for pointing this out!
