### ISSUE TITLE
what does action not handled means?

### ISSUE THREAD

**Issue by yogeshdcool** [anishathalye/dotfiles_template#23]
I have this in my install.conf.yaml
- clean: ['~']

- link:
  ~/.config/nvim: nvim/

and copied ~/.config/nvim to the dotfiles repo but ./install show
An error was encountered while executing action link
Action link not handled
Action ~/.config/nvim not handled

==> Some tasks were not executed successfully
how to fix that

I don't know where else to ask help

**Comment by anishathalye** [comment]
Could you upload the yaml file directly, so I can see the original formatting?

I think the indentation might be wrong. Try indending the `~/.config/nvim: nvim/` by two more spaces.

**Comment by anishathalye** [comment]
Assuming this is resolved, feel free to reopen if not.
